### ISSUE TITLE
Error starting the project with this package

### ISSUE THREAD

**Issue by brilvio** [wesleyyoung/perch-query-builder#3]
**Describe the bug**
After installing the module the project breaks

```bash

node_modules/perch-query-builder/dist/constants/index.d.ts:1:15 - error TS2307: Cannot find module './ASC' or its corresponding type declarations.

1 export * from './ASC';
                ~~~~~~~

node_modules/perch-query-builder/dist/constants/index.d.ts:2:15 - error TS2307: Cannot find module './DESC' or its corresponding type declarations.

2 export * from './DESC';
                ~~~~~~~~

node_modules/perch-query-builder/dist/constants/index.d.ts:3:15 - error TS2307: Cannot find module './ORDER' or its corresponding type declarations.

3 export * from './ORDER';
                ~~~~~~~~~

node_modules/perch-query-builder/dist/types/query-order.d.ts:1:10 - error TS2305: Module '"../constants"' has no exported member 'ORDER'.

1 import { ORDER } from "../constants";
           ~~~~~
```

**To Reproduce**
1 - Install the module
2 - Start the project

**Expected behavior**
Works

**Screenshots**
![image](https://user-images.githubusercontent.com/4560552/108858540-0a817800-75cb-11eb-80e3-98f6a4500939.png)

As you can see it is exporting `ASC` (uppercase) but the file is in lowercase, looking at the repository the file is named in uppercase as well, I think you need to push a new version to npm.

**Desktop (please complete the following information):**
- Linux (Ubuntu)
- Version of the package: 1.1.14

**Comment by brilvio** [comment]
I cloned the repository and yeah the version on NPM differs from the version here.

![image](https://user-images.githubusercontent.com/4560552/108861673-41a55880-75ce-11eb-818d-8a24d1ea20b8.png)

**Comment by wesleyyoung** [comment]
I just re-published to npm with updated patch version 1.1.15. Is it working for you now?

**Comment by brilvio** [comment]
Yes, thanks for this package as well it is really helpfull.

**Comment by wesleyyoung** [comment]
No problem. If you have ideas for features or implementation feel free to message me or submit a PR
