### ISSUE TITLE
Question: Is there a way to use `FindManyOptions<Type>` with `PerchQueryBuilder`?

### ISSUE THREAD

**Issue by Migushthe2nd** [wesleyyoung/perch-query-builder#7]
Using the built-in repository `find()` method, it is possible to _find_ with many different options (image below)
![image](https://user-images.githubusercontent.com/22274715/130670934-73126812-7ce1-4364-97ca-ee2cb4b95e3a.png)

Is there a way to specify such options with `PerchQueryBuilder`?

**Comment by wesleyyoung** [comment]
Can you clarify your question? Are you asking if it is possible to use a method such as `PerchQueryBuilder.select` ?

**Comment by wesleyyoung** [comment]
Are you asking if you can supply additional filter params on top of the query?

This is actually possible if you instead use `const qb = PerchQueryBilder.generateQueryBuilder(this.bookRepository, info)`

and attach additional AND WHERE clauses. The generateQueryBuilder method returns a TypeORM QueryBuilder

**Comment by Migushthe2nd** [comment]
Ah I see, I can always use the general querybuilder, however, I prefer the simplicity of `Repository.find()`.
This allows one to do quite a lot actually, even filter on nested types.
A simple example would be:
```ts
bookRepository.find({
    where: {
        status: In(["Free", "Sale"])
        publisher: {
            id: "5b"
        }
    }
})
```

**Edit:**
The `QueryBuilder`'s `where()` method accepts an object of type `FindOptions<Type>`.
(`queryBuilder.where(findOptions)`)
